server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sdn?serverTimezone=GMT%2b8
      username: root
      password: root
  devtools:
    livereload:
      enabled: true
